### ISSUE TITLE
Everything now works or not?    

### ISSUE THREAD

**Issue by ahadrox** [masterchiefvn/Hackintosh-Gigabyte-B460M-AORUS-PRO-OPENCORE#1]
Hi there, please confirm that everything is working fine. And also do mention if you are facing any issues, bugs. Thanks.

**Comment by masterchiefvn** [comment]
> Hi there, please confirm that everything is working fine. And also do mention if you are facing any issues, bugs. Thanks.

Thank you for your contribution. I have updated Readme.md
